# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Initialise
        run: |
          $PSVersionTable

          git config --global user.email "david@gardiner.net.au"
          git config --global user.name "flcdrg"
          git config --global core.safecrlf false

          choco install vt-cli -y

          Write-Output "Configuring AU"
          git clone -q https://github.com/flcdrg/chocolatey-au.git $Env:TEMP/au
          Set-Location $Env:TEMP/au
          . "./scripts/Install-AU.ps1" fix-warnings

          Get-InstalledModule | Select-Object Name, Version, InstalledLocation
        shell: pwsh
        env:
          github_api_key: ${{ secrets.GH_API_KEY }}

      - name: Update
        run: ./update_all.ps1 -Name resharper-platform,teamcity,*.portable,*.install
        shell: pwsh
        env:
          github_api_key: ${{ secrets.GH_API_KEY }} # GitHub API Key
          api_key: ${{ secrets.API_KEY }} # Chocolatey API Key
          VT_APIKEY: ${{ secrets.VT_APIKEY }} # VirusTotal API Key
          au_push: true
          gist_id: 7d00c69c2cde8309a8594abaa897a9a6
          github_user_repo: flcdrg/au-packages
        
      
